export const ADMIN_NAV = [
  { href: "/admin", label: "Dashboard", dot: "bg-zinc-400 dark:bg-zinc-500", platformOnly: false },
  { href: "/admin/societies", label: "Societies", dot: "bg-teal-500", platformOnly: true },
  { href: "/admin/residents", label: "Residents", dot: "bg-sky-500", platformOnly: false },
  { href: "/admin/maintenance", label: "Maintenance", dot: "bg-amber-500", platformOnly: false },
  { href: "/admin/ledger", label: "Ledger", dot: "bg-lime-500", platformOnly: false },
  { href: "/admin/complaints", label: "Complaints", dot: "bg-rose-500", platformOnly: false },
  { href: "/admin/visitors", label: "Visitors", dot: "bg-violet-500", platformOnly: false },
  { href: "/admin/guards", label: "Guards", dot: "bg-cyan-500", platformOnly: false },
  { href: "/admin/notices", label: "Notices", dot: "bg-emerald-500", platformOnly: true },
  { href: "/admin/roles", label: "Roles", dot: "bg-fuchsia-500", platformOnly: false },
  { href: "/admin/users", label: "Users", dot: "bg-indigo-500", platformOnly: true },
  { href: "/admin/support", label: "Support", dot: "bg-orange-500", platformOnly: true },
  { href: "/admin/audit", label: "Audit log", dot: "bg-slate-500", platformOnly: true },
] as const;
